# Generated by Django 4.1.5 on 2023-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_de_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
